# Generated by Django 4.1.5 on 2023-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateur_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(default=170),
        ),
    ]
